import * as fs from "fs";
import * as path from "path";
import fg from "fast-glob";

export class Parser {
    private _namespace: string;
    private _metadata: any;
    private _resolve: any;
    private _cwd: string;

    constructor(namespace: string, metadata: any, resolve: any, cwd: string){
        this._namespace = namespace;
        this._metadata = metadata;
        this._resolve = resolve;
        this._cwd = cwd;
    }

    async export(){
        let scriptText = `// Auto-generated by Blueprint \n
import * as path from "path";
import { Subject } from 'rxjs';
import { Blueprint, Type, Flow } from "@ucsjs/blueprint";\n`;

        for(let item of this._metadata.items){
            scriptText += `const { ${item.namespace} } = require(path.resolve("${await this.resolve(item.namespace)}"));\n`;
        }

        scriptText += `\nexport class ${this._namespace} extends Blueprint { \n`;

        if(this._metadata.items){
            scriptText += `\texec(){\n`;
            scriptText += `\t\tconst subject = new Subject<any>();\n\n`;
            scriptText += `\t\tnew Flow({\n`;

            for(let item of this._metadata.items){
                scriptText += `\t\t\t${item.namespace.toLowerCase()}: new ${item.namespace}(),\n`;
            }

            scriptText += `\t\t}, subject)\n`;
            
            if(this._metadata.connections){
                for(let connection of this._metadata.connections){
                    const input = this.getInput(connection.from.component, connection.from.input);
                    const output = this.getInput(connection.to.component, connection.to.input);
                    scriptText += `\t\t.subscribe("${connection.from.component.toLowerCase()}", "${input}", "${connection.to.component.toLowerCase()}", "${output}")\n`;
                }
            }

            scriptText += `\t\t.start();\n\n`;
            scriptText += `\t\treturn subject;\n`;
            scriptText += `\t}\n`;
        }

        scriptText += `}\n\n`;

        scriptText += `export default ${this._namespace};\n`;

        return scriptText;
    }

    getInput(component, inputId){
        for(let item of this._metadata.items){
            if(item.namespace == component){
                for(let input of item.inputs){
                    if(input.id == inputId){
                        return input.name;
                    }
                }

                for(let input of item.outputs){
                    if(input.id == inputId){
                        return input.name;
                    }
                }
            }
        }
    }

    async resolve(namespace){
        for(let key in this._resolve)
            this._resolve[key] = path.resolve(this._resolve[key]);
        
        const files = await fg(this._resolve, { dot: true, onlyFiles: true });
        
        for(let file of files){
            const content = fs.readFileSync(file, "utf-8");
            
            if(content.indexOf(namespace) > -1){
                return file.replace(`${this._cwd}/`, "");
            }
        }
    }
}