// Auto-generated by Blueprint 

import * as path from "path";
import { Subject } from 'rxjs';
import { Blueprint, Flow } from "@ucsjs/blueprint";
const { HTTPInBlueprint } = require(path.resolve("src/blueprints/Network/httpin.blueprint.ts"));
const { MongoFindBlueprint } = require(path.resolve("src/blueprints/mongoFind.blueprint.ts"));
const { MongoConnectionBlueprint } = require(path.resolve("src/blueprints/mongoConnection.blueprint.ts"));

export class HelloworldBlueprint extends Blueprint { 
	exec(){
		const subject = new Subject<any>();

		new Flow({
			httpinblueprint0: new HTTPInBlueprint({"controller":"/todo","routes":[{"url":"/"},{"url":"/add","method":"POST"},{"url":"/edit","method":"PUT"},{"url":"/del","method":"DELETE"}]}),
			mongofindblueprint1: new MongoFindBlueprint(),
			mongoconnectionblueprint2: new MongoConnectionBlueprint(),
		}, subject)
		.subscribe("mongoconnectionblueprint2", "connection", "mongofindblueprint1", "connection")
		.start();

		return subject;
	}
}

export default HelloworldBlueprint;
