// Auto-generated by Blueprint 

import { Subject } from 'rxjs';
import { Blueprint, Flow } from "@ucsjs/blueprint";
import { HTTPInBlueprint } from "src/blueprints/Network/httpIn.blueprint";
import { HTTPOutBlueprint } from "src/blueprints/Network/httpOut.blueprint";
import { MongoConnectionBlueprint } from "node_modules/@ucsjs/mongodb/src/blueprints/mongoConnection.blueprint";
import { MongoSchemaBlueprint } from "node_modules/@ucsjs/mongodb/src/blueprints/mongoSchema.blueprint";
import { HTTPParamBlueprint } from "src/blueprints/Network/httpParam.blueprint";
import { MongoFindBlueprint } from "node_modules/@ucsjs/mongodb/src/blueprints/mongoFind.blueprint";

export class HelloworldBlueprint extends Blueprint {
	exec(args?: any){
		const subject = new Subject<any>();

		const flow = new Flow({
			httpinblueprint0: new HTTPInBlueprint({"stateId":1663190885523,"itemKey":"0","controller":"/todo","routes":[{"url":"/","key":"c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-0"},{"url":"/:id","key":"c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-1"},{"url":"/","method":"POST","key":"c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-2"}]}),
			httpoutblueprint1: new HTTPOutBlueprint(),
			mongoconnectionblueprint2: new MongoConnectionBlueprint({"stateId":1663190885523,"itemKey":"2","protocol":"mongodb+srv","host":"soucrypto-ea71c61c.mongo.ondigitalocean.com","ignorePort":true,"user":"doadmin","pass":"2w6yh91t3J7pA4L5","db":"soucrypto","replicaSet":"soucrypto","tls":true}),
			mongoschemablueprint3: new MongoSchemaBlueprint({"stateId":1663190885523,"itemKey":"3","collection":"todo","timestamps":true,"fields":[{"name":"id","index":true,"required":true,"key":"0201a0411d7de880c8bd40d11274259eb733a0a9-5-0"},{"name":"title","index":false,"required":true,"key":"0201a0411d7de880c8bd40d11274259eb733a0a9-5-1"}]}),
			httpparamblueprint4: new HTTPParamBlueprint({"stateId":1663190885523,"itemKey":"4","name":"id","toJSON":true}),
			mongofindblueprint5: new MongoFindBlueprint(),
			mongofindblueprint6: new MongoFindBlueprint({"stateId":1663190885523,"itemKey":"6","query":{}}),
			httpoutblueprint7: new HTTPOutBlueprint(),
		}, subject, args);

		flow.subscribe("httpinblueprint0", "c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-0", "httpoutblueprint1", "request")
		flow.subscribe("mongoconnectionblueprint2", "connection", "mongoschemablueprint3", "connection")
		flow.subscribe("httpinblueprint0", "c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-1", "httpparamblueprint4", "request")
		flow.subscribe("mongoschemablueprint3", "schema", "mongofindblueprint6", "schema")
		flow.subscribe("mongoschemablueprint3", "schema", "mongofindblueprint5", "schema")
		flow.subscribe("mongofindblueprint6", "result", "httpoutblueprint1", "contents")
		flow.subscribe("httpparamblueprint4", "result", "mongofindblueprint5", "query")
		flow.subscribe("httpinblueprint0", "c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-1", "httpoutblueprint7", "request")
		flow.subscribe("mongofindblueprint5", "result", "httpoutblueprint7", "contents")
		flow.start();

		return { flow, subject };
	}
}

import { Controller, Req, Res, Get, Post, Put, Delete, Patch } from "@nestjs/common";
import { Request, Response } from "express";
import { Document, Model, createConnection } from "mongoose";
import { MongooseModule, Prop, Schema, SchemaFactory, InjectModel } from '@nestjs/mongoose';
const mongodb_2 = createConnection("mongodb+srv://doadmin:2w6yh91t3J7pA4L5@soucrypto-ea71c61c.mongo.ondigitalocean.com/soucrypto?replicaSet=soucrypto&tls=true&authSource=admin");

@Controller("/todo")
export class HelloworldBlueprintController {
    constructor(	){}

    @Get("/")
    async helloworldblueprintget_(@Req() req: Request, @Res() res: Response){
        const { subject, flow } = new HelloworldBlueprint().exec({mongodb_2, TodoSchema});
		flow.get("httpoutblueprint1").subscribe("output", (data) => { if(data) res.status(200).send(data); });
		flow.get("httpinblueprint0").next("c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-0", req);
    }

    @Get("/:id")
    async helloworldblueprintget_id(@Req() req: Request, @Res() res: Response){
        const { subject, flow } = new HelloworldBlueprint().exec({mongodb_2, TodoSchema});
		flow.get("httpoutblueprint7").subscribe("output", (data) => { if(data) res.status(200).send(data); });
		flow.get("httpinblueprint0").next("c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-1", req);
    }

    @Post("/")
    async helloworldblueprintpost_(@Req() req: Request, @Res() res: Response){
        const { subject, flow } = new HelloworldBlueprint().exec({mongodb_2, TodoSchema});		flow.get("httpinblueprint0").next("c782a1bf7f74c0a22eb8d764d6b7c9ba20300670-0-2", req);
    }
}

export interface Todo {
	id: string;
	title: string;
};

@Schema({ timestamps: true, collection: "todo" })
export class TodoDocument extends Document implements Todo {
	@Prop({ required: true, index:true, type: String, unique: false })
        id: string;

	@Prop({ required: true, index:false, type: String, unique: false })
        title: string;
};

export const TodoSchema = SchemaFactory.createForClass(TodoDocument);
import { Module } from "@nestjs/common";

@Module({
    imports: [
		
	],
    exports: [
		
	],
    controllers: [
		HelloworldBlueprintController
	],
    providers: [
		
	]
})
export class LazyModule {}