// Auto-generated by Blueprint 

import { Subject } from 'rxjs';
import { Blueprint, Flow } from "@ucsjs/blueprint";
import { CounterBlueprint } from "src/blueprints/Common/counter.blueprint";
import { HashBlueprint } from "src/blueprints/Encoding/hash.blueprint";

export class TodoBlueprint extends Blueprint {
	exec(args?: any){
		const subject = new Subject<any>();

		const flow = new Flow({
			counterblueprint0: new CounterBlueprint(),
			hashblueprint1: new HashBlueprint(),
		}, subject, args);

		flow.subscribe("counterblueprint0", "counter", "hashblueprint1", "state")
		flow.output("hashblueprint1", "result")
		flow.start();

		return { flow, subject };
	}
}

