// Auto-generated by Blueprint 

import * as path from "path";
import { Subject } from 'rxjs';
import { Blueprint, Type, Flow } from "@ucsjs/blueprint";
const { ConsoleBlueprint } = require(path.resolve("src/blueprints/Debug/console.blueprint.ts"));
const { CounterBlueprint } = require(path.resolve("src/blueprints/Common/counter.blueprint.ts"));

export class HelloworldBlueprint extends Blueprint { 
	exec(){
		const subject = new Subject<any>();

		new Flow({
			consoleblueprint: new ConsoleBlueprint(),
			counterblueprint: new CounterBlueprint(),
		}, subject)
		.subscribe("counterblueprint", "counter", "consoleblueprint", "message")
		.start();

		return subject;
	}
}

export default HelloworldBlueprint;
